<a href="https://colab.research.google.com/github/Farukkibria/introduction/blob/main/Assignment_3_NumPy_and_Pandas_for_Data_Science_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Student Performance Dataset Analysis
Dataset Information
Student Performance Dataset (StudentsPerformance.csv)

1000 students with academic performance data
8 columns: gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score
Score Range: 0-100 for each subject
Demographics: Male/Female, 5 ethnic groups, 6 education levels, standard/free lunch, test prep completed/none
"""

In [3]:
#Task 1.1: Data Loading and Exploration
import numpy as np
import pandas as pd
from google.colab import files
uploaded = files.upload()

# Load the uploaded file
import io
df = pd.read_csv(io.BytesIO(uploaded['StudentsPerformancenew5.csv']))

# Load the dataset
#df = pd.read_csv('StudentsPerformance.csv')

# Your tasks:
# 1. Display first 10 rows
# 2. Show dataset shape and info()
# 3. Display unique values in each categorical column
# 4. Show basic statistics for all score columns

# Your code here:
print(df[1:10])
print("shape :", df.shape)
print("info", df.info)
print(df.describe())

Saving StudentsPerformancenew5.csv to StudentsPerformancenew5.csv
   gender race/ethnicity parental level of education         lunch  \
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard
5  female        group B          associate's degree      standard
6  female        group B                some college      standard
7    male        group B                some college  free/reduced
8    male        group D                 high school  free/reduced
9  female        group B                 high school  free/reduced

  test preparation course  math score  reading score  writing score
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75
5                    none          71             83             78
6               completed          88             95             92
7                    none          40             43             39
8               completed          64             64             67
9                    none          38             60             50
shape : (1000, 8)
info <bound method DataFrame.info of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>
       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [4]:
#Task 1.2: NumPy Array Operations
# Convert score columns to numpy arrays
math_scores = df['math score'].values
reading_scores = df['reading score'].values
writing_scores = df['writing score'].values

# Your tasks:
# 1. Calculate mean, median, std, min, max for each subject using NumPy
# 2. Find total students who scored above 80 in math
# 3. Find total students who scored below 50 in any subject
# 4. Calculate the overall average score across all three subjects

# Expected output example:
# Math - Mean: 66.1, Median: 66.0, Std: 15.2
# Students with math > 80: 132
# Students with any score < 50: 178

# Your code here:
print("math scores info:\n")
print("mean:", np.mean(math_scores))
print("median:", np.median(math_scores))
print("std:", np.std(math_scores))
print("min:", np.min(math_scores))
print("max:", np.max(math_scores))
print("reading score info:")
print("mean:", np.mean(reading_scores))
print("median:", np.median(reading_scores))
print("std:", np.std(reading_scores))
print("min:", np.min(reading_scores))
print("max:", np.max(reading_scores))
print("writing scores info/n:")
print("mean:", np.mean(writing_scores))
print("median:", np.median(writing_scores))
print("std:", np.std(writing_scores))
print("min:", np.min(writing_scores))
print("max:", np.max(writing_scores))
math_ab_80=(math_scores>80)
print("total above 80 in math:",np.sum(math_ab_80))
math_bl_50=(math_scores<50)
print("total below 50 in math:",np.sum(math_bl_50))
reading_bl_50=(reading_scores<50)
print("total below 50 in reading:",np.sum(reading_bl_50))
writing_bl_50=(writing_scores<50)
print("total below 50 in writing:",np.sum(writing_bl_50))
total= np.sum(math_bl_50)+np.sum(reading_bl_50)+np.sum(writing_bl_50)
print("total below 50:", total)
tot=(np.mean(math_scores)+np.mean(reading_scores)+np.mean(writing_scores))/3
print("overall average score:",tot)

math scores info:

mean: 66.089
median: 66.0
std: 15.155496659628149
min: 0
max: 100
reading score info:
mean: 69.169
median: 70.0
std: 14.592890015346516
min: 17
max: 100
writing scores info/n:
mean: 68.054
median: 69.0
std: 15.188057281956768
min: 10
max: 100
total above 80 in math: 176
total below 50 in math: 135
total below 50 in reading: 90
total below 50 in writing: 114
total below 50: 339
overall average score: 67.77066666666666

In [5]:
# Task 2.1: Identify and Handle Missing Data
# Check the dataset for any missing values
# Your tasks:
# 1. Check for null values in each column using .isnull().sum()
# 2. Check for any impossible values (scores > 100 or < 0)
# 3. Display summary of data quality

# Note: This dataset is clean, but let's verify!

# Your code here:
null_math=df['math score'].isnull().sum()
print(null_math)
null_reading=df['reading score'].isnull().sum()
print(null_reading)
null_writing=df['writing score'].isnull().sum()
print(null_writing)
impossible_values= (df['math score']<0) & (df['math score']>100).sum()
print ("\n impossible values:\n",impossible_values)

0
0
0

 impossible values:
 0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: math score, Length: 1000, dtype: bool

In [20]:
#Task 2.2: Create and Fix Missing Value
# Artificially create missing data for practice
import numpy as np

# Your tasks:
# 1. Make a copy of the dataset: df_practice = df.copy()
# 2. Randomly set 50 math scores to np.nan
# 3. Randomly set 30 writing scores to np.nan
# 4. Fill missing math scores with the MEDIAN math score
# 5. Fill missing writing scores with the MEAN writing score
# 6. Verify no missing values remain

# Steps to follow:
# Step 1: Create copy and show original missing values
df_practice = df.copy()
print("Original missing values:", df_practice.isnull().sum())

# Step 2: Create missing data
np.random.seed(42)  # For reproducible results
missing_math_idx = np.random.choice(df_practice.index, 50, replace=False)
missing_writing_idx = np.random.choice(df_practice.index, 30, replace=False)
print("missing math",missing_math_idx)
print('missing writing',missing_writing_idx)
df_practice ["math score"]=df_practice ["math score"].replace(missing_math_idx,np.nan)
print('math score with nan',df_practice ["math score"])
df_practice ["math score"]=df_practice ["math score"].replace(np.nan,df_practice ["math score"].mean())
print('math score with avg',df_practice ["math score"])
df_practice ["writing score"]=df_practice ["writing score"].replace(missing_writing_idx,np.nan)
print('writing score with nan',df_practice ["writing score"])
df_practice ["writing score"]=df_practice ["writing score"].replace(np.nan,df_practice ["writing score"].mean())
print('writing score with avg',df_practice ["writing score"])
print("Final missing values:", df_practice.isnull().sum())
# Continue the task...
# Your code here:

Original missing values: gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64
missing math [521 737 740 660 411 678 626 513 859 136 811  76 636 973 938 899 280 883
 761 319 549 174 371 527 210 235 101 986 902 947 346 139 621 499 370 198
 687 584 901  59 328  96 312 974 299 277 924 601 439 837]
missing writing [ 93 692 100 562 729 924 393 685 738 264 172 314 870 983  70   9 361 444
 857 855  90  47 812 861 456  56  66 469 967 420]
math score with nan 0      72.0
1      69.0
2      90.0
3      47.0
4       NaN
       ...
995    88.0
996    62.0
997     NaN
998    68.0
999    77.0
Name: math score, Length: 1000, dtype: float64
math score with avg 0      72.000000
1      69.000000
2      90.000000
3      47.000000
4      66.013771
         ...
995    88.000000
996    62.000000
997    66.013771
998    68.000000
999    77.000000
Name: math score, Length: 1000, dtype: float64
writing score with nan 0      74.0
1      88.0
2       NaN
3      44.0
4      75.0
       ...
995    95.0
996    55.0
997    65.0
998    77.0
999    86.0
Name: writing score, Length: 1000, dtype: float64
writing score with avg 0      74.000000
1      88.000000
2      67.488162
3      44.000000
4      75.000000
         ...
995    95.000000
996    55.000000
997    65.000000
998    77.000000
999    86.000000
Name: writing score, Length: 1000, dtype: float64
Final missing values: gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
#Task 3.1:Answer Simple Questions About Student Performance
# Your tasks:
# 1. Display first 5 rows using .head()
# 2. Display last 5 rows using .tail()
# 3. Show dataset shape using .shape
# 4. Show column names using .columns
# 5. Show data types using .dtypes
# 6. Show basic info using .info()

# Your code here:
print ("first 5 rows:\n", df.head())
print ("last 5 rows:\n", df.tail())
print ("shape:\n", df.shape)
print ("Math Score:\n", df["math score"])
print ("Reading Score:\n", df["reading score"])
print ("Writing Score:\n", df["writing score"])
print(df.columns)
print(df.dtypes)
print(df.info())

first 5 rows:
    gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75
last 5 rows:
      gender race/ethnicity parental level of education         lunch  \
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86
shape:
 (1000, 8)
Math Score:
 0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64
Reading Score:
 0      72
1      90
2      95
3      57
4      78
       ..
995    99
996    55
997    71
998    78
999    86
Name: reading score, Length: 1000, dtype: int64
Writing Score:
 0      74
1      88
2      93
3      44
4      75
       ..
995    95
996    55
997    65
998    77
999    86
Name: writing score, Length: 1000, dtype: int64
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')
gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [ ]:
#Task 3.2: Basic Groupby Analysis
# Comprehensive groupby analysis
# Your tasks:

# 1. Group by 'gender' and calculate:
#    - Average scores in all subjects
#    - Count of students

# 2. Group by 'test preparation course' and show:
#    - Mean scores for each subject
#    - Show which subject benefits most from test prep

# 3. Group by 'parental level of education' and calculate:
#    - Average math score for each education level
#    - Rank education levels by math performance

# 4. Group by 'lunch' type and show:
#    - Average scores for each subject
#    - Count of students in each lunch category

# Your code here:
summary = df.groupby('gender')[['math score','reading score','writing score']].mean()
siz = df.groupby('gender')[['math score', 'reading score', 'writing score']].size()
print("Summary by gender:")
print(summary)
total_scor=summary.sum(axis=1)/3
print(total_scor)
print(siz)
summ = df.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean()
print("Summary by test preparation course:")
print(summ)
summa = df.groupby('parental level of education')[['math score']].mean()
print("Summary by parental level of education:")
print(summa)
ranking=summa.rank()
print("ranking:",ranking)
print("length", len(summa))
summar = df.groupby('lunch')[['math score', 'reading score', 'writing score']].mean()
summaryy = df.groupby('lunch')[['math score', 'reading score', 'writing score']].size()
print("Summary by launch provided:")
print(summar)
print(summaryy)
print ("Math average:",df['math score'].mean())
print ("Reading average:",df['reading score'].mean())
print ("Writing average:",df['writing score'].mean())

Summary by gender:
        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203
gender
female    69.569498
male      65.837483
dtype: float64
gender
female    518
male      482
dtype: int64
Summary by test preparation course:
                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
Summary by parental level of education:
                             math score
parental level of education
associate's degree            67.882883
bachelor's degree             69.389831
high school                   62.137755
master's degree               69.745763
some college                  67.128319
some high school              63.497207
ranking:                              math score
parental level of education
associate's degree                  4.0
bachelor's degree                   5.0
high school                         1.0
master's degree                     6.0
some college                        3.0
some high school                    2.0
length 6
Summary by launch provided:
              math score  reading score  writing score
lunch
free/reduced   58.921127      64.653521      63.022535
standard       70.034109      71.654264      70.823256
lunch
free/reduced    355
standard        645
dtype: int64
Math average: 66.089
Reading average: 69.169
Writing average: 68.054

In [ ]:
#Task 3.3: Use your data analysis skills to answer these easy questions:
summarr = df.groupby('parental level of education')[['math score','reading score', 'writing score']].mean()
total_score=summarr.sum(axis=1)/3
print(total_score)
# 1. Who performs better in math - males or females? male
#    - Calculate average math score by gender;  male=68.7, female=63.6
#    - Show the difference between male and female average; difference=5.1

# 2. Which subject do students perform best in overall?
#    - Calculate the overall average for math, reading, and writing; math=66.1; reading=69.1; writing=68.1
#    - Rank the subjects from highest to lowest average score; 1=reading; 2=writing; 3=Math

# 3. What's the impact of parental education?
#    - Find the average total score for each parental education level
#    - Identify which education level leads to highest student performance (masters degree)

parental level of education
associate's degree    69.569069
bachelor's degree     71.923729
high school           63.096939
master's degree       73.598870
some college          68.476401
some high school      65.108007
dtype: float64